"""
AlgoFlow Contract Builder & TEAL Compiler Utilities.
"""

from __future__ import annotations

import base64
import enum
from typing import Any, Dict, Optional, Tuple

from algosdk import logic
from algosdk.transaction import StateSchema

from algoflow.contracts import CLEAR_STATE_PATH, ESCROW_APPROVAL_PATH


class BountyStatus(int, enum.Enum):
    OPEN = 0
    CLAIMED = 1
    RESOLVED = 2
    CLOSED = 3
    REFUNDED = 4

    @property
    def label(self) -> str:
        return self.name.replace("_", " ")


class EscrowContractBuilder:
    """
    Manages TEAL source code, state schema, and deployment preparation
    for AlgoFlow bounty escrow smart contracts.
    """

    # Global State:
    # 3 byte slices: "creator", "bounty_id", "technician", "evidence_hash" -> Actually 4 bytes!
    # 3 ints: "amount", "deadline", "status"
    # To be safe and future-proof on Algorand:
    GLOBAL_BYTE_SLICES = 4
    GLOBAL_INTS = 3
    LOCAL_BYTE_SLICES = 0
    LOCAL_INTS = 0

    @classmethod
    def get_approval_source(cls) -> str:
        """Read TEAL approval program source from disk."""
        return ESCROW_APPROVAL_PATH.read_text(encoding="utf-8")

    @classmethod
    def get_clear_state_source(cls) -> str:
        """Read TEAL clear program source from disk."""
        return CLEAR_STATE_PATH.read_text(encoding="utf-8")

    @classmethod
    def get_global_schema(cls) -> StateSchema:
        """Returns the StateSchema for global storage."""
        return StateSchema(
            num_uints=cls.GLOBAL_INTS,
            num_byte_slices=cls.GLOBAL_BYTE_SLICES,
        )

    @classmethod
    def get_local_schema(cls) -> StateSchema:
        """Returns the StateSchema for local account storage."""
        return StateSchema(
            num_uints=cls.LOCAL_INTS,
            num_byte_slices=cls.LOCAL_BYTE_SLICES,
        )

    @classmethod
    def encode_creation_args(
        cls,
        bounty_id: str,
        amount_microalgos: int,
        deadline_round: int,
    ) -> list[bytes]:
        """
        Encode the 3 creation arguments:
        - Arg 0: bounty_id (bytes utf-8)
        - Arg 1: amount in microAlgos (8 bytes big-endian)
        - Arg 2: deadline round (8 bytes big-endian)
        """
        return [
            bounty_id.encode("utf-8"),
            amount_microalgos.to_bytes(8, "big"),
            deadline_round.to_bytes(8, "big"),
        ]

    @classmethod
    def compute_application_address(cls, app_id: int) -> str:
        """
        Computes the Algorand escrow address generated by the application ID.
        """
        return logic.get_application_address(app_id)

    @classmethod
    def parse_global_state(cls, raw_state: list[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Decodes raw key-value pairs returned by Algod / Indexer global state.
        """
        parsed: Dict[str, Any] = {}
        for item in raw_state:
            key_raw = item.get("key", "")
            try:
                key = base64.b64decode(key_raw).decode("utf-8")
            except Exception:
                key = key_raw

            val_dict = item.get("value", {})
            val_type = val_dict.get("type", 0)

            if val_type == 1:  # bytes
                raw_bytes = base64.b64decode(val_dict.get("bytes", ""))
                if key in ("creator", "technician") and len(raw_bytes) == 32:
                    from algosdk import encoding
                    parsed[key] = encoding.encode_address(raw_bytes)
                elif key == "evidence_hash":
                    parsed[key] = raw_bytes.hex()
                else:
                    try:
                        parsed[key] = raw_bytes.decode("utf-8")
                    except UnicodeDecodeError:
                        parsed[key] = raw_bytes.hex()
            elif val_type == 2:  # uint
                parsed[key] = val_dict.get("uint", 0)

        if "status" in parsed and isinstance(parsed["status"], int):
            try:
                parsed["status_label"] = BountyStatus(parsed["status"]).label
            except ValueError:
                parsed["status_label"] = f"UNKNOWN ({parsed['status']})"

        return parsed
